### ISSUE TITLE
Android: assignment name is cut from the bottom in student profile page

### ISSUE THREAD

**Issue by ElyDev** [KhalidPM/YungDevz#148]
![image](https://user-images.githubusercontent.com/7612136/57259061-2ccf8d80-7013-11e9-8bef-13d73f4d57c8.png)

**Comment by khalidelho** [comment]
so what do you suggest to do here? should we increase the box size if the notes are alot

**Comment by ElyDev** [comment]
Can you try increasing the height of the assignment card by a couple of pixels, then in the styles of the assignment title add paddingBottom: 2 (or if there is padding already then add a couple more pixels to it)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by khalidelho** [comment]
I actually fixed the issue by removing the padding completely and i did it where you are able to press on the card to see any extra notes

**Comment by ElyDev** [comment]
Masha'allah. That is awesome. Great job!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by khalidelho** [comment]
Also i want to make apull request how do i do that

**Comment by ElyDev** [comment]
Launch github desktop, then review and commit your changes, then press Ctrl+R on github desktop (Or go to Branch in the menu and select: Create pull request)

**Comment by khalidelho** [comment]
ok JAK

**Comment by khalidelho** [comment]
Do you know why no GitHub notifications are coming anymore event to the engineering channel

**Comment by ElyDev** [comment]
Because we removed it from the settings yesterday. Do you want to enable them back?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by khalidelho** [comment]
we removed it but we directed it to engineering correct?

**Comment by khalidelho** [comment]
so the new messages should eb coming at engineering but they are not
